CREATE TABLE Presensi 
		(PresensiId INT IDENTITY(1,1),
		Tanggal DATETIME NOT NULL DEFAULT ('2024-01-01'),
		Jam TIME NOT NULL DEFAULT ('00:00'),
		KelasId INT NOT NULL DEFAULT (0),
		MapelId INT NOT NULL DEFAULT (0),
		GuruId INT NOT NULL DEFAULT (0),
		SiswaId INT NOT NULL DEFAULT (0),
		Kehadiran INT NOT NULL DEFAULT (0),
		Keterangan VARCHAR(50) NOT NULL DEFAULT (0),
		
		CONSTRAINT PK_Presensi PRIMARY KEY (PresensiId))
