CREATE TABLE JadwalPelajaran 
	(JadwalId INT IDENTITY(1,1),
	 KelasId INT NOT NULL DEFAULT(0),

	 Hari VARCHAR(10) NOT NULL DEFAULT (''),
	 JenisJadwal	VARCHAR(6) NOT NULL DEFAULT(''),
	 JamMulai VARCHAR(6) NOT NULL DEFAULT (''),
	 JamSelesai VARCHAR(6) NOT NULL DEFAULT(''),

	 MapelId INT NOT NULL  DEFAULT(0),
	 GuruId INT NOT NULL DEFAULT(0),
	 Keterangan VARCHAR(50) NOT NULL DEFAULT (''),

	 CONSTRAINT PK_JadwalPelajaran PRIMARY KEY CLUSTERED(JadwalId)
	 )

	 DROP TABLE JadwalPelajaran	